services:
  db:
    image: 'mariadb:10.11'
    container_name: chatapp-db
    restart: always
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./database/chat_app.sql:/docker-entrypoint-initdb.d/chat_app.sql
      - mariadb_data:/var/lib/mysql

  app:
    container_name: chatapp-backend
    depends_on:
      - db
    build: ./
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/chat_app?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: Y2hhdEFwcFN1cGVyU2VjcmV0S2V5Rm9ySldUVG9rZW5TaWduaW5nMTIzNDU2Nzg5MDEyMzQ1Ng==
    volumes:
      - ./uploads:/uploads

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: chatapp-phpmyadmin
    restart: always
    ports:
      - '8181:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
    depends_on:
      - db

volumes:
  mariadb_data: