version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

   #Autre service
  db:
    # Image MariaDB à utiliser
    image: 'mariadb'
    # Redémarrer toujours en cas d'erreur fatale
    restart: always
    # Variables d'environnement pour configurer la base de données
    environment:
      MYSQL_DATABASE: chat_app
      MYSQL_ROOT_PASSWORD: password
    # Mappage du port 3306 du conteneur sur le port 3306 de l'hôte (localhost)
    ports:
      - "3306:3306"
    # Montage du fichier SQL pour l'initialisation de la base de données
    volumes:
      - ./database/chat_app.sql:/docker-entrypoint-initdb.d/chat_app.sql

  #Encore un autre service
  phpmyadmin:
    #image utiliser phpmyadmin
    image: phpmyadmin
    #Si erreur fatal redémarage
    restart: always
    #Port du conteneur
    ports:
      - '8181:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql